name: containerize

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_PREFIX: ghcr.io/${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      - name: login-ghcr
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: extract-version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: build-docker-image
        run: |
          REPO_PREFIX_LOWER=$(echo "$REPO_PREFIX" | tr '[:upper:]' '[:lower:]')
          docker build -t $REPO_PREFIX_LOWER:${{ steps.version.outputs.VERSION }} -f Dockerfile .
          docker push $REPO_PREFIX_LOWER:${{ steps.version.outputs.VERSION }}
          docker tag $REPO_PREFIX_LOWER:${{ steps.version.outputs.VERSION }} $REPO_PREFIX_LOWER:latest
          docker push $REPO_PREFIX_LOWER:latest
